============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-7.4.4, pluggy-1.4.0
cachedir: /home/vincent/gz/ws_inspect/build/inspection_thermal/.pytest_cache
rootdir: /home/vincent/gz/ws_inspect/src/inspection_thermal
plugins: launch-testing-ros-0.26.9, ament-pep257-0.17.3, ament-lint-0.17.3, launch-testing-3.4.6, ament-copyright-0.17.3, ament-xmllint-0.17.3, ament-flake8-0.17.3, colcon-core-0.20.0, cov-4.1.0
collected 1 item

tests/test_thermal_alarm.py E                                            [100%]

==================================== ERRORS ====================================
_______________ ERROR at setup of test_alarm_engages_and_clears ________________
tests/test_thermal_alarm.py:19: in rclpy_runtime
    rclpy.init()
/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/__init__.py:88: in init
    context.init(args, domain_id=domain_id)
/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/context.py:106: in init
    _rclpy.rclpy_logging_configure(self.__context)
E   RuntimeError: Failed opening file /home/vincent/.ros/log/python3_279195_1759424259902.log for writing: Permission denied
- generated xml file: /home/vincent/gz/ws_inspect/build/inspection_thermal/pytest.xml -
=========================== short test summary info ============================
ERROR tests/test_thermal_alarm.py::test_alarm_engages_and_clears - RuntimeErr...
=============================== 1 error in 0.63s ===============================
